- hosts: primary_to_upgrade
  become: yes
  gather_facts: no
  tasks:
    - name: Set Mongo Feature Compatibility Version
      shell: "python {{ src_path }}/mongoup.py set_compatibility_version_for_upgrade {{ target_version }}"

- hosts: secondary_to_upgrade:primary_to_upgrade
  become: yes
  gather_facts: no
  tasks:
    - name: get env package info
      package_facts:
        manager: auto
    - name: Install mongodb-base18 rpm package
      shell: "rpm -ivh {{ src_path }}/mongodb-base18-*.rpm"
      args:
        warn: false
      when: '"mongodb-base18" not in ansible_facts.packages'

- hosts: secondary_to_upgrade
  serial: 1
  become: yes
  gather_facts: no
  tasks:
    - name: Upgrade mongo rpm package
      shell: "rpm -Uvh {{ src_path }}/mongodb-server-{{ target_version }}*.rpm"
      args:
        warn: false
    - name: Restart mongod.service
      systemd:
        name: mongod.service
        state: restarted
        daemon_reload: yes
    - name: Wait for mongo cluster status, Retry for 120 times
      shell: "python {{ src_path }}/mongoup.py check_mongo_cluster_states"
      register: result
      until: result.rc == 0
      retries: 120
      delay: 5

- hosts: primary_to_upgrade
  serial: 1
  become: yes
  gather_facts: no
  tasks:
    - name: Stepdown current primary node
      shell: "python {{ src_path }}/mongoup.py step_down_old_version_primary {{ target_version }}"
      args:
        warn: false
    - name: Clean mongo data directory
      shell: "/bin/rm -rf /var/lib/mongodb/*"
      args:
        warn: false
    - name: Upgrade mongo rpm package
      shell: "rpm -Uvh {{ src_path }}/mongodb-server-{{ target_version }}*.rpm"
      args:
        warn: false
    - name: Restart mongod.service
      systemd:
        name: mongod.service
        state: restarted
        daemon_reload: yes
    - name: Wait for mongo cluster status, Retry for 120 times
      shell: "python {{ src_path }}/mongoup.py check_mongo_cluster_states"
      register: result
      until: result.rc == 0
      retries: 120
      delay: 5
