- hosts: secondary_to_upgrade:primary_to_upgrade
  serial: 1
  become: yes
  gather_facts: no
  tasks:
    - name: get env package info
      package_facts:
        manager: auto
    - name: Install mongodb-base16  rpm package
      shell: "rpm -ivh {{ src_path }}/mongodb-base16-*.rpm"
      args:
        warn: false
      when: '"mongodb-base16" not in ansible_facts.packages'

- hosts: secondary_to_upgrade
  serial: 1
  become: yes
  gather_facts: no
  tasks:
    - name: Stop following mongo secondary node
      systemd:
        name: mongod.service
        state: stopped
    - name: Clean mongo data directory
      shell: "/bin/rm -rf /var/lib/mongodb/*"
      args:
        warn: false
    - name: Upgrade mongo rpm package
      shell: "rpm -Uvh {{ src_path }}/mongodb-server-{{ target_version }}*.rpm"
      args:
        warn: false
    - name: Restart mongod.service
      systemd:
        name: mongod.service
        state: restarted
        daemon_reload: yes
    - name: Wait for mongo cluster status, Retry for 120 times
      shell: "python {{ src_path }}/mongoup.py check_mongo_cluster_states {{ down_node }}"
      register: result
      until: result.rc == 0
      retries: 120
      delay: 10

- hosts: primary_to_upgrade
  serial: 1
  become: yes
  gather_facts: no
  tasks:
    - name: Stop mongo primary node
      systemd:
        name: mongod.service
        state: stopped
    - name: Clean mongo data directory
      shell: "/bin/rm -rf /var/lib/mongodb/*"
      args:
        warn: false
    - name: Upgrade mongo rpm package
      shell: "rpm -Uvh {{ src_path }}/mongodb-server-{{ target_version }}*.rpm"
      args:
        warn: false
    - name: Restart mongod.service
      systemd:
        name: mongod.service
        state: restarted
        daemon_reload: yes
    - name: Wait for mongo cluster status, Retry for 120 times
      shell: "python {{ src_path }}/mongoup.py check_mongo_cluster_states {{ down_node }}"
      register: result
      until: result.rc == 0
      retries: 120
      delay: 10
